apiVersion: v1
kind: Service
metadata:
  name: {{ include "freqtrade.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "freqtrade.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: webui
      protocol: TCP
      name: webui
  selector:
    {{- include "freqtrade.selectorLabels" . | nindent 4 }}
